#!/usr/bin/env python

#  -*- python -*-
#  ------------------------------------------------------------------
#  Derek A. Rhodes, Tue Jun  7 13:48:36 EDT 2011

import sys

from optparse import OptionParser

def cmdline():
    usage = "hey, like so: $ %prog infile [options]"
    parser = OptionParser(usage)

    parser.add_option("-t", 
                      "--take", 
                      dest="take",
                      type="int",
                      default=1,  
                      help="Take a number of lines to show")

    parser.add_option("-d",
                      "--drop",
                      dest="drop",
                      type="int",
                      default=0, #seconds.
                      help="drop this number of lines")
    
    (options, args) = parser.parse_args()

    skip_lines(args, options)

def skip_lines(args, kw):
    takes = kw.take
    drops = kw.drop

    lines = iter(sys.stdin.readlines())

    try:
        while lines:
            for i in range(takes):
                sys.stdout.write(lines.next())
            for i in range(drops):
                lines.next()
    except StopIteration:
        sys.exit()

cmdline()
            


